#!/bin/bash

CONCOURSE_CI=Concourse
JENKINS_CI=jenkins

SONAR_USER=admin
SONAR_PASSWORD=passwd

#ACTIVATE or DEACTIVATE
minikubeOn=$ACTIVATE
istioOn=$DEACTIVATE
#CONCOURSE_CI or JENKINS_CI ..... concourse is not supported yt
ci=$JENKINS_CI

MAX_WAIT_SEC_JENKINS=60
MAX_WAIT_SEC_SONAR=60