#!/bin/bash

JENKINS_KUBERNETTES=jenkinsKub
JENKINS_VM=jenkinsVm
LOCAL_REGISTRY=localhost
JFOG_REGISTRY=jfog

SONAR_USER=admin
SONAR_PASSWORD=passwd

#ACTIVATE or DEACTIVATE
minikubeOn=$ACTIVATE
istioOn=$DEACTIVATE
#JENKINS_VM or JENKINS_KUBERNETTES.....
ci=$JENKINS_VM
registry=$JFOG_REGISTRY

MAX_WAIT_SEC_JENKINS=60
MAX_WAIT_SEC_SONAR=60

LIB_VERSION=wip-0.2.0