version: '3.3'
services:
  vault:
    image: vault:local
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ../volumes/vault/logs:/vault/logs
      - ../volumes/vault/file:/vault/file
      - ../volumes/vault/unseal:/vault/unseal
      - ../volumes/vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    environment:
     - VAULT_API_ADDR=http://127.0.0.1:8200