jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: passwd
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
unclassified:
  location:
    url: localhost:8080/